# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: windows-2022

steps:

- task: UiPathTest@4
  inputs:
    testTarget: 'TestSet'
    orchestratorConnection: 'Staging'
    testSet: 'DemoTestSet'
    folderName: '360° Test Suite Demo'
    attachRobotLogs: true